device: 'cuda:0'
lr: 0.0001
batch_size: 4096

model_spec:

  input_size: [28, 28]
  num_input_channels: 1
  num_output_layer_channels: 256
  num_classes: 10

  supernet_layers:
  - out_channels: 32
    blocks:
      conv3x3:
        kind: conv2d
        kernel_size: 3
      conv5x5:
        kind: conv2d
        kernel_size: 5
  - out_channels: 32
    blocks:
      conv3x3:
        kind: conv2d
        kernel_size: 3
      conv5x5:
        kind: conv2d
        kernel_size: 5

model_configuration: random
