device: 'cpu'
lr: 0.01
batch_size: 1024
num_epoch: 100
early_stopping_patience: 5
seed: 42

model_spec:

  input_size: [28, 28]
  num_input_channels: 1
  num_output_layer_channels: 64
  num_classes: 10

  supernet_layers:
  - out_channels: 16
    blocks:
      conv3x3:
        kind: conv2d
        kernel_size: 3
      conv5x5:
        kind: conv2d
        kernel_size: 5
  - out_channels: 32
    blocks:
      conv3x3:
        kind: conv2d
        kernel_size: 3
      conv5x5:
        kind: conv2d
        kernel_size: 5

model_configuration:

  - conv3x3
  - conv3x3
